import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './../components/Header';
import Banner from './../components/Banner';
import SmallCard from '../components/SmallCard';
import MediumCard from './../components/MediumCard';
import LargCard from '../components/LargCard';
import Footer from './../components/Footer';

export default function Home({exploreData,cardsData}) {
  return (
    <div >
      <Head>
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>
      <main className='max-w-6xl mx-auto px-8'>
        <section className='pt-6 '>
          <h2 className='text-4xl font-semibold pd-5'>Explore</h2>

          {/* pull some data from API endpoint*/}
          <div className='grid grid-cols-1 sm:grid-cols-2  lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData.map(({img,location,distance})=>(
              <SmallCard 
              key={img}
              img={img}
              location={location}
              distance ={distance}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {cardsData?.map(({img,title})=>(
              <MediumCard 
              // className=" m-7  "
              key={img}
              img={img}
              title={title}
              />
            ))}
          </div>
        </section>
        <LargCard
        img="https://links.papareact.com/4cj"
        title="The Greatest Outdoors"
        description="Wishlists curated by Airbnb"
        buttonText="Get Inspired"
        />
      </main>
        <Footer/>
    </div>
  )
}

export async function getStaticProps(){
 const exploreData= await fetch("https://links.papareact.com/pyp").then(
   (res)=>res.json()
 ) ;

const cardsData=await fetch("https://links.papareact.com/zp1").then(
  (res)=>res.json()
);



 return{
   props:{
     exploreData,
     cardsData,
   }
 }
}